- hosts: workers
  become: yes
  gather_facts: yes

  tasks:
    - name: Check if node already joined
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: Get fresh kubeadm join command from master
      command: kubeadm token create --print-join-command
      register: join_cmd
      delegate_to: "{{ groups['master'][0] }}"
      run_once: true
      when: not kubelet_conf.stat.exists

    - name: Save join command to script on master
      copy:
        content: "{{ join_cmd.stdout }}"
        dest: /tmp/kubeadm_join.sh
        mode: '0755'
      delegate_to: "{{ groups['master'][0] }}"
      run_once: true
      when: not kubelet_conf.stat.exists

    - name: Fetch join script from master
      fetch:
        src: /tmp/kubeadm_join.sh
        dest: /tmp/kubeadm_join.sh
        flat: yes
      delegate_to: "{{ groups['master'][0] }}"
      run_once: true
      when: not kubelet_conf.stat.exists

    - name: Push join script to worker
      copy:
        src: /tmp/kubeadm_join.sh
        dest: /tmp/kubeadm_join.sh
        mode: '0755'
      when: not kubelet_conf.stat.exists

    - name: Join cluster with retry
      shell: sh /tmp/kubeadm_join.sh
      register: join_result
      retries: 3
      delay: 30
      until: join_result.rc == 0
      when: not kubelet_conf.stat.exists
    # --------------------------------------------------
    # Wait for cloud-init to finish (CRITICAL)
    # --------------------------------------------------
    - name: Wait for cloud-init to finish
      shell: cloud-init status --wait
      changed_when: false

    # --------------------------------------------------
    # Configure kubelet AWS providerID (REQUIRED FOR ALB)
    # --------------------------------------------------
    - name: Configure kubelet with AWS providerID
      shell: |
        INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)

        mkdir -p /etc/systemd/system/kubelet.service.d

        cat <<EOF >/etc/systemd/system/kubelet.service.d/20-aws-provider.conf
        [Service]
        Environment="KUBELET_EXTRA_ARGS=--cloud-provider=aws --provider-id=aws:///ap-south-1/$INSTANCE_ID"
        EOF

    - name: Reload and restart kubelet
      shell: |
        systemctl daemon-reexec
        systemctl daemon-reload
        systemctl restart kubelet

   